version: "3"

services:
    mysqld:
        image: mysql:latest
        container_name: farmer-system
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mabera
            MYSQL_PORT: "3306"
        volumes:
            - mysql-data:/var/lib/mysql
       

    farmer-app:
        image: mabera/farmersystem:latest
        ports:
            - "8080:8080"
        depends_on:
            - mysqld
        environment:
            MYSQL_HOST: mysqld
        

volumes:
    mysql-data: