version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.12-jdk-buster

    working_directory: ~/repo

    steps:
      - checkout

      # Setup JDK
      - run:
          name: Install JDK
          command: sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-11.0.12/bin/java 1

      # Restore dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Build
      - run:
          name: Build
          command: mvn clean package

      # Run tests
      - run:
          name: Run Tests
          command: mvn test

  deploy:
    machine:
      enabled: default

    steps:
      - checkout

      # Here goes the deployment steps, it could be deploying to a server, a cloud provider, etc.
