# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:latest
#           resources:
#             limits:
#               memory: 512Mi
#               cpu: "1"
#             requests:
#               memory: 256Mi
#               cpu: "0.2"
#           env:
#             - name: MYSQL_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secret
#                   key: password
#             - name: MYSQL_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-user
#                   key: user-name
#           ports:
#             - containerPort: 3306
#               name: mysql
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#       volumes:
#         - name: mysql-persistent-storage
#           emptyDir: {}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
# spec:
#   selector:
#     app: mysql
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#   clusterIP: None


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: development
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
