apiVersion: v1
data:
  username: cm9vdA==
  password: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: "2024-02-12T08:56:47Z"
  name: assetmanager-secret
  resourceVersion: "18669"
  uid: 1e6f4df9-f38c-4671-8c9f-39c261ffc056
type: Opaque